config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :goals do
      resources :entries
    end
    resources :users do
      resources :entries
    end
  end

  resources :tags do
    get :show
  end

  resources :friendships

  devise_for :users

  resources :users do
    get :feed
    get :show
    get :followers
    get :following
    get :accomplished
  end

  resources :goals do
    member do
      patch :completed
      patch :incomplete
    end
    resources :entries do
      resources :comments
      member do
        post :cheer
        patch :uncheer
      end
    end
  end

  get 'pages/api'
  get 'pages/recent'

  root 'goals#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  default_scope -> { order('created_at DESC') }
  belongs_to :user
  belongs_to :entry
  validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update,
    :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
    @goal = Goal.find(params[:goal_id])
    @entry = Entry.find(params[:entry_id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @entry = Entry.find(params[:entry_id])
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.entry_id = @entry.id

    respond_to do |format|
      if @comment.save
        format.html { redirect_to :back, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { redirect_to :back, alert: "Comment can't be blank" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    @goal = Goal.find(params[:goal_id])
    @entry = Entry.find(params[:entry_id])
      if @comment.update(comment_params)
        redirect_to goal_entry_path(@goal, @entry),
        notice: 'Comment was successfully updated.'
      else
        render :edit,
        alert: 'Comment was not updated.'
      end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def check_user
      unless @comment.user == current_user || current_user.admin?
        redirect_to root_url, alert: 'You are not authorized.'
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([@goal, @entry, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='form-group'>
    <span class="glyphicon glyphicon-comment"></span>&nbsp;
    <%= f.label :body, 'Comment' %>
    <%= f.text_area :body, class: 'form-control', rows: '3' %>
  </div>
  <div class='form-group'>
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= form_for(@comment, url: goal_entry_comment_path) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body, 'Comment' %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Back', goal_entry_path(@goal, @entry) %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>