config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :goals do
      resources :entries
    end
    resources :users do
      resources :entries
    end
  end

  resources :tags do
    get :show
  end

  resources :friendships

  devise_for :users

  resources :users do
    get :feed
    get :show
    get :followers
    get :following
    get :accomplished
  end

  resources :goals do
    member do
      patch :completed
      patch :incomplete
    end
    resources :entries do
      resources :comments
      member do
        post :cheer
        patch :uncheer
      end
    end
  end

  get 'pages/api'
  get 'pages/recent'

  root 'goals#index'

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  default_scope -> { order('created_at DESC') }
  belongs_to :user
  belongs_to :goal
  has_many :cheers, dependent: :destroy
  has_many :cheering_users, through: :cheers, source: :user
  has_many :comments, dependent: :destroy
  validates :content, presence: true, length: { maximum: 2000 }

  def cheered?(user)
    if self.cheering_users.include?(user)
      return true
    else
      return false
    end
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :uncheer, :cheer, :edit, :update, :destroy]
  before_action :set_goal
  before_action :authenticate_user!, only: [:cheer, :uncheer, :new, :create, :edit, :update,
    :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]
  before_action :entry_goal_user?, only: [:new, :create]
  before_action :set_cheerers, only: [:cheer, :uncheer, :show]
  before_action :previous_entry, only: [:show]
  before_action :next_entry, only: [:show]

  def cheer
    @cheered = @entry.cheers.create(user_id: current_user.id)

    if @cheered.save
      respond_to do |format|
        flash.now[:notice] = "Thank you for cheering!"
        format.js { render 'cheer' }
      end
    else
      flash.now[:alert] = "You have already cheered this."
      redirect_to :back
    end
  end

  def uncheer
    Cheer.destroy_all(entry_id: @entry.id, user_id: current_user.id)

    respond_to do |format|
      flash.now[:alert] = "You have uncheered this entry."
      format.js { render 'cheer' }
    end
  end

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
    @comment = Comment.new
    @comments = @entry.comments.paginate(page: params[:page], per_page: 10)
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)
    @entry.goal_id = @goal.id
    @entry.user_id = current_user.id

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @goal, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to :back, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to @goal, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # returns next entry
    def next_entry
      container = @goal.entries.select { |obj| obj.id > @entry.id }
      @next = container.sort_by(&:id).first
    end
    # returns previous entry
    def previous_entry
      container = @goal.entries.select { |obj| obj.id < @entry.id }
      @previous = container.sort_by(&:id).last
    end
    # return array of entry cheerers
    def set_cheerers
      @cheerers = @entry.cheering_users.limit(10)
    end
    # set goal id for entries
    def set_goal
      @goal = Goal.find(params[:goal_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    def entry_goal_user?
      unless @goal.user == current_user
        redirect_to root_url, alert: 'You are not authorized.'
      end
    end

    def check_user
      unless @entry.user == current_user || current_user.admin?
        redirect_to root_url, alert: 'You are not authorized.'
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:content)
    end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_cheer.html.erb
<!-- Cheer & Edit/Delete Entry Controls -->

<!-- Cheer/Uncheer Entry -->
<% if user_signed_in? %>
<!-- Show cheer links if signed in -->
  <% if @entry.cheered?(current_user) %>
    <%= link_to "Thanks!", uncheer_goal_entry_path(@goal, @entry), method: :patch, remote: true %>
  <% else %>
      <%= link_to "Cheer!",
    cheer_goal_entry_path(@goal, @entry), method: :post, remote: true %>&nbsp;
  <% end %>
<!-- Redirect to Sign In page if not signed in -->
<% else %>
  <%= link_to "Cheer!",
    new_user_session_path %>&nbsp;
<% end %>

app/views/entries/_cheerers.html.erb
<ul>
  <% @cheerers.to_a.each do |user| %>
    <li><strong><%= link_to user.username.titleize, user %></strong> cheered this.</li>
  <% end %>
  <% unless @entry.cheering_users.count <= 10 %>
    <li>...and <strong><%= "#{@entry.cheering_users.count - 10}" %></strong> other users cheered this.</li>
  <% end %>
</ul>

app/views/entries/_comments.html.erb
<div class="comments">
  <% @comments.each do |comment| %>
    <div class="comment-block">
      <p>
        <strong>
          <%= link_to comment.user.username.titleize, comment.user %>&nbsp;says:
        </strong>
      </p>

      <blockquote>
        <%= comment.body %>
      </blockquote>

      <hr>

      <p>
        posted <strong><%= time_ago_in_words(comment.created_at) %></strong> ago
      </p>

      <p class="comment-controls">
        <% if authorized_user?(comment) %>
          <%= link_to 'Edit',
          edit_goal_entry_comment_path(@goal, @entry, comment) %>&nbsp;
        <% end %>

        <% if authorized_user?(@entry) %>
          &nbsp;<%= link_to 'Destroy', [@goal, @entry, comment], method: :delete,
          data: { confirm: 'Are you sure you want to delete this comment?' } %>
        <% end %>
      </p>
    </div>
  <% end %>
</div>

<div class="text-center">
  <p class="pagination">
    <%= will_paginate @comments, renderer: BootstrapPagination::Rails %>
  </p>
</div>

app/views/entries/_control.html.erb
<!-- Edit/Destroy Entry -->
  <% if authorized_user?(@entry) %>
    <%= link_to 'Edit', edit_goal_entry_path(@goal, @entry) %>&nbsp;|
    <%= link_to 'Destroy', [@goal, @entry], method: :delete,
    data: { confirm: 'Are you sure you want to delete this entry?' } %>
  <% end %>

app/views/entries/_form.html.erb
<%= form_for([@goal, @entry]) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/cheer.js.erb
$(".flash").html('<%= j render "layouts/flash" %>');
$(".entry-cheer-count").html('<%= "#{@entry.cheering_users.count} cheers" %>');
$(".entry-cheerers").html("<%= j render partial: 'cheerers', cheerers: @cheerers %>");
$(".cheer-control").html("<%= j render partial: 'cheer' %>");

app/views/entries/edit.html.erb
<%= link_to 'Back to Goal', goal_path(@goal) %>

<h1>Editing Entry</h1>

<%= render 'form' %>

app/views/entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Entries</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.content %></td>
        <td><%= link_to 'Show', entry %></td>
        <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
        <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entry', new_entry_path %>

app/views/entries/new.html.erb
<h1>New Entry</h1>

<%= render 'form' %>

<%= link_to 'Back', goal_path(@goal) %>

app/views/entries/show.html.erb
<div class="container entry-page">

<!-- Entry Information -->
<p>
  <strong>
    <%= link_to @entry.user.username.titleize, @entry.user %>
    <%= " wants to " %>
    <%= link_to @entry.goal.description, goal_path(@goal) %>
  </strong>
</p>

<!-- Previous/Next Arrows -->
<p class="arrow">

  <% unless @previous.nil? %>
    <%= link_to "<span class='glyphicon glyphicon-arrow-left'></span>".html_safe, goal_entry_path(@goal, @previous), class: 'arrow' %>
  <% end %>

  <% unless @next.nil? %>
    &nbsp;
    <%= link_to "<span class='glyphicon glyphicon-arrow-right'></span>".html_safe, goal_entry_path(@goal, @next), class: 'arrow' %>
  <% end %>

</p>

  <!-- Main Entry Content -->
  <div class="content">

    <!-- Edit/Delete Links -->
    <p class="entry-page-control">
      <%= render 'control' %>
    </p>

    <section>
      <%= @entry.content %>
    </section>

    <p class="clear"></p>

    <hr>

    <ul class="cheer-master">
    <!-- Entry Cheer Count -->
      <li class="entry-cheer-count cheer-count">
        <%= "#{@entry.cheering_users.count} cheers" %>
      </li>

      <!-- Cheer Entry -->
      <li class="cheer-control">
        <%= render 'cheer' %>
      </li>

    </ul>
    <!-- Entry Created At -->
    <p class="entry-created">
      posted <strong><%= time_ago_in_words(@entry.created_at) %></strong> ago.
    </p>
  </div>

  <!-- Entry Cheerers -->
  <p class="entry-cheerers">
    <%= render 'cheerers' %>
  </p>

  <!-- Comments Form -->
  <p class="comment-form">
    <%= render partial: 'comments/form', goal: @goal %>
  </p>

  <!-- Entry Comments -->
  <%= render 'comments' %>
</div>