config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :goals do
      resources :entries
    end
    resources :users do
      resources :entries
    end
  end

  resources :tags do
    get :show
  end

  resources :friendships

  devise_for :users

  resources :users do
    get :feed
    get :show
    get :followers
    get :following
    get :accomplished
  end

  resources :goals do
    member do
      patch :completed
      patch :incomplete
    end
    resources :entries do
      resources :comments
      member do
        post :cheer
        patch :uncheer
      end
    end
  end

  get 'pages/api'
  get 'pages/recent'

  root 'goals#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  include Gravtastic
  gravtastic
  has_many :goals, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :cheers, dependent: :destroy
  has_many :cheered_entries, through: :cheers, source: :entry
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships
  has_many :reverse_relationship, class_name: 'Friendship',
  foreign_key: 'friend_id'
  has_many :followers, through: :reverse_relationship, source: :user
  validates :username, presence: true
  validates_uniqueness_of :username
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  def to_param
    username
  end

  def completed_goals
    self.goals.where(completed: true).count
  end

  def following?(user)
    self.friendships.find_by(friend_id: user.id).present?
  end

  def activity
    all = []
    self.friendships.each do |user|
      user.friend.goals.each do |item|
        unless item.private == true
          all << item
          item.entries.each do |entry|
            all << entry
          end
        end
      end
    end
    all.sort_by(&:created_at).reverse
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  def show
    user = User.find_by_username(params[:id])
    goals = user.goals.where(private: false)
    render json: goals.each.as_json(include:[:entries])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user_id, only: [:accomplished, :following, :followers, :feed]

  def accomplished
    if current_user == @user
      @goals = @user.goals.where(completed: true).paginate(page: params[:page], per_page: 20)
    else
      @goals = @user.goals.where(completed: true).where(private: false).paginate(page: params[:page], per_page: 20)
    end
  end

  def following
  end

  def followers
  end

  def feed
    @activity = @user.activity.paginate(page: params[:page], per_page: 20)
  end

  def show
    @user = User.find_by_username(params[:id])
    @goals = @user.goals.paginate(page: params[:page], per_page: 20)
  end

  private

  # set :user_id for friendships
  def set_user_id
    @user = User.find_by_username(params[:user_id])
  end
end

app/views/users/_friends.html.erb
<ul class="user-friends">

  <li class="followers">Followers (<%= link_to @user.followers.count,
  user_followers_path(@user) %>)</li>

  <li class="following">Following (<%= link_to @user.friendships.count,
  user_following_path(@user) %>)</li>

</ul>

app/views/users/_goals.html.erb
<div class="row">
  <% @goals.each do |goal| %>

  <% unless goal.private? && current_user != @user && !current_user.try(:admin?) %>

    <div class="col-sm-3 text-center">
      <div class="home-padding<% if goal.private? %><%= " private" %><% end %>">

          <p>
            <%= link_to image_tag(goal.user.gravatar_url, class: 'avatar'), goal.user %>
          </p>

          <p>
            <strong><%= link_to goal.user.username.titleize, goal.user %></strong>
            <%= " wants to " %>
            <strong><%= link_to goal.description, goal %></strong>
          </p>

          <div class="control">
            <p>
              <span><% if goal.completed? %><em>completed</em><% end %></span>
            </p>

            <!-- Only show View button if current user is not profile user -->
              <% if current_user != @user %>
                <p><%= link_to "View", goal, class: 'btn btn-default' %></p>
              <% end %>

              <% if authorized_user?(goal) %>
                <%= link_to 'Edit', edit_goal_path(goal), class: 'btn btn-default' %>&nbsp;
                <%= link_to 'Destroy', goal, method: :delete,
                data: { confirm: 'Are you sure?' }, class: 'btn btn-default' %>
              <% end %>
          </div>
      </div>
    </div>

  <% end %><!-- End of Unless Statement -->
  <% end %><!-- End of Each Block -->
</div>

<div class="text-center">
    <p class="pagination">
      <%= will_paginate @goals, renderer: BootstrapPagination::Rails %>
    </p>
  </div>
</div>

app/views/users/accomplished.html.erb
<h1><%= @user.username %>'s Completed Goals</h1>

<% @goals.each do |goal| %>
  <p>
  <strong><%= link_to @user.username, @user %></strong> wants to <strong><%= link_to goal.description, goal %></strong>
  </p>
<% end %>

app/views/users/feed.html.erb
<h1>Activity</h1>

<ul>
  <% @activity.each do |obj| %>
    <% if obj.has_attribute?(:description) %>
      <li>
      <strong><%= link_to obj.user.username, obj.user %></strong> posted
      <span><strong><%= link_to obj.description, obj %></strong></span>
      at <span><strong><%= time_ago_in_words(obj.created_at) %></strong><span>
      ago.
      </li>
    <% else %>
      <li>
      <strong><%= link_to obj.user.username, obj.user %></strong> posted
      <span><strong><%= link_to obj.content, obj.goal %></strong></span>
      at <span><strong><%= time_ago_in_words(obj.created_at) %></strong></span>
      ago.
      </li>
    <% end %>
  <% end %>
</ul>

<%= will_paginate @activity %>

app/views/users/followers.html.erb
<h2>Followers</h2>
<ul class="followers">
  <% @user.followers.each do |user| %>
    <li>
      <%= link_to user.username, user %>
    </li>
  <% end %>
</ul>

app/views/users/following.html.erb
<h2>Following</h2>
<ul class="following">
  <% @user.friendships.each do |user| %>
    <li>
    <%= link_to user.friend.username, user.friend %>
    <span><%= link_to 'unfollow', user, method: :delete %></span>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<!-- Jumbotron -->
<div class="jumbotron profile-bg">
</div>

  <!-- User Basic Information -->
    <div class="profile-container text-center">
      <%= image_tag @user.gravatar_url, class: 'profile-avatar avatar' %>

      <div class="user-basics">
        <h1 class="username"><%= @user.username.titleize %></h1>

        <p class="completed-count"><%= link_to @user.completed_goals, user_accomplished_path(@user) %> Goals Completed</p>

        <!-- Show Followers and Following -->
          <%= render 'friends' %>

        <!-- Activity Feed for Profile User -->
          <% unless !user_signed_in? || current_user != @user %>
            <p><%= link_to 'Activity Feed', user_feed_path(@user) %></p>
          <% end %>

        <!-- Follow/Unfollow Buttons -->
          <p>
            <% if user_signed_in? && current_user != @user %>
              <% if current_user.following?(@user) %>
                <%= render partial: 'friendships/unfollow' %>
              <% else %>
                <%= render partial: 'friendships/follow' %>
              <% end %>
            <% end %>
          </p>
      </div>
  </div>

  <div class="container user-goals">
    <!-- List User's Goals -->
      <h4><span class='glyphicon glyphicon-list'></span>&nbsp;&nbsp;<%= "#{@user.username.titleize}'s Goals" %></span></h4>

        <%= render 'goals' %>

  </div><!-- End Container-->