config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :goals do
      resources :entries
    end
    resources :users do
      resources :entries
    end
  end

  resources :tags do
    get :show
  end

  resources :friendships

  devise_for :users

  resources :users do
    get :feed
    get :show
    get :followers
    get :following
    get :accomplished
  end

  resources :goals do
    member do
      patch :completed
      patch :incomplete
    end
    resources :entries do
      resources :comments
      member do
        post :cheer
        patch :uncheer
      end
    end
  end

  get 'pages/api'
  get 'pages/recent'

  root 'goals#index'

end

app/models/goal.rb
class Goal < ActiveRecord::Base
  default_scope -> { order('created_at DESC') }
  belongs_to :user
  has_many :entries, dependent: :destroy
  has_many :taggings
  has_many :tags, through: :taggings
  validates :description, presence: true, length: { maximum: 40 }

  def completed?
    self.completed == true
  end

  def private?
    self.private == true
  end

  def tag_list
    tags.map(&:name).join(", ")
  end

# tag setter in goal form
  def tag_list=(names)
    self.tags = names.split(",").map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end
end

app/controllers/api/goals_controller.rb
class Api::GoalsController < ApplicationController
  def index
    render json: Goal.all
  end

  def show
    goal = Goal.find(params[:id])
    if goal.private?
      render status: 422, json: {
        message: "Could not retrieve goal.",
      }.to_json
    else
      render json: goal.as_json(include:[:entries])
    end
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: [:incomplete, :completed, :show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:incomplete, :completed, :new, :create, :edit, :update,
    :destroy]
  before_action :check_user, only: [:incomplete, :completed, :edit, :update, :destroy]

  def completed
    @goal.update(completed: true)
    redirect_to :back, notice: "Goal has been marked as completed!"
  end

  def incomplete
    @goal.update(completed: false)
    redirect_to :back, notice: "Goal has been marked as incomplete."
  end

  # GET /goals
  # GET /goals.json
  def index
    @goals = Goal.where(private: false).limit(16)
  end

  # GET /goals/1
  # GET /goals/1.json
  def show
    if @goal.private? && current_user != @goal.user
      redirect_to root_url, alert: "You are not authorized."
    else
      @user = @goal.user
      @entries = @goal.entries.all.paginate(page: params[:page],
      per_page: 10)
    end
  end

  # GET /goals/new
  def new
    @goal = Goal.new
  end

  # GET /goals/1/edit
  def edit
  end

  # POST /goals
  # POST /goals.json
  def create
    @goal = Goal.new(goal_params)
    @goal.user_id = current_user.id

    respond_to do |format|
      if @goal.save
        format.html { redirect_to @goal, notice: 'Goal was successfully created.' }
        format.json { render :show, status: :created, location: @goal }
      else
        format.html { render :new }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goals/1
  # PATCH/PUT /goals/1.json
  def update
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to @goal, notice: 'Goal was successfully updated.' }
        format.json { render :show, status: :ok, location: @goal }
      else
        format.html { render :edit }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1
  # DELETE /goals/1.json
  def destroy
    @goal.destroy
    respond_to do |format|
      format.html { redirect_to goals_url, notice: 'Goal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      @goal = Goal.find(params[:id])
    end

    def check_user
      unless @goal.user == current_user || current_user.admin?
        redirect_to root_url, alert: 'You are not authorized.'
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goal_params
      params.require(:goal).permit(:description, :private, :name, :tag_list, :completed)
    end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_completed.html.erb
<% if user_signed_in? && @goal.user == current_user %>
  <p>
  <% if !@goal.completed? %>
    <%= link_to 'Mark as Completed.', completed_goal_path(@goal), method: :patch, class: "btn btn-sm btn-warning btn-visited btn-goal" %>
  <% else %>
    <%= link_to 'Goal Completed.', incomplete_goal_path(@goal), method: :patch, class: "btn btn-sm btn-success btn-visited btn-goal" %>
  <% end %>
  </p>
<% end %>

app/views/goals/_control.html.erb
<% if authorized_user?(@goal) %>
  <p class="control">
    <%= link_to 'Edit', edit_goal_path(@goal) %>&nbsp;&nbsp;|&nbsp;
    <%= link_to 'Destroy', @goal, method: :delete,
    data: { confirm: 'Are you sure you want to delete this goal?' } %>
  </p>
<% end %>

app/views/goals/_entries.html.erb
<ul class="entries">
  <% unless @goal.entries.blank? %>
    <% @goal.entries.each do |entry| %>

      <li class="entry">
        <p><%= h truncate(entry.content, length: 1000) %></p>

      <hr>

      <div class="entry-control">
        <%= link_to "View Entry", goal_entry_path(@goal, entry) %>&nbsp;
        <span class="cheer-count"><%= "#{entry.cheering_users.count} cheers" %></span>&nbsp;

        <!-- Entry Edit/Destroy Links -->
        <% if authorized_user?(entry) %>
          <p class="goal-page-entry-control">
            <%= link_to 'Edit', edit_goal_entry_path(@goal, entry) %>&nbsp;&nbsp;|&nbsp;
            <%= link_to 'Destroy', [@goal, entry], method: :delete,
            data: { confirm: 'Are you sure you want to delete this entry?' } %>
          </p>
        <% end %>
      </div>

      <p class="created">
        posted <strong><%= time_ago_in_words(entry.created_at) %></strong> ago.
      </p>
      </li>

          <p>
    <% end %>
  <% else %>
    <!-- If no entries -->
    <li class="no-entries">No Entries</li>
  <% end %>
</ul>

<div class="text-center">
  <p class="pagination">
    <%= will_paginate @entries, renderer: BootstrapPagination::Rails %>
  </p>
</div>

app/views/goals/_form.html.erb
<%= form_for(@goal) do |f| %>
  <% if @goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

      <ul>
      <% @goal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description, "Description (max characters: 30)" %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :tag_list, "Tags (separated by commas)" %><br>
    <%= f.text_field :tag_list %>
  </div>
  <div class="field">
    <%= f.label :private, "Private?" %><br>
    <%= f.check_box :private, id: "private" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/goals/edit.html.erb
<h1>Editing Goal</h1>

<%= render 'form' %>

<%= link_to 'Show', @goal %> |
<%= link_to 'Back', goals_path %>

app/views/goals/index.html.erb
<!-- Jumbotron -->
<div class="jumbotron">
  <div class="text-container">
    <h1>Carpe Diem</h1>
      <p class="lead">Seize the Day!</p>
      <p>Free blogging platform to share your goals and progress.</p>
      <p><%= link_to "Sign Up for Free", new_user_registration_path, class: "btn btn-lg btn-success btn-visited", role: "button" %></p>
  </div>
</div>

<div class="container">

  <h4><span class='glyphicon glyphicon-list'></span>&nbsp;&nbsp;Recent Goals</h4>
  <!-- Goals Limit 16 -->
  <div class="row">

      <% @goals.each do |goal| %>

      <div class="col-sm-3 text-center">
        <div class="home-padding">
          <p>
            <%= link_to image_tag(goal.user.gravatar_url, class: 'avatar'), goal.user %>
          </p>

          <p>
            <strong><%= link_to goal.user.username.titleize, goal.user %></strong>
            <%= " wants to " %>
            <strong><%= link_to goal.description, goal %></strong>
          </p>

          <p><%= link_to "View", goal, class: 'btn btn-default' %></p>

        </div>
      </div>

      <% end %>
  </div>

  <p><%= link_to 'View More', pages_recent_path, class: 'btn btn-lg btn-success view-more btn-visited' %></p>

  <h4><span class='glyphicon glyphicon-tags'></span>&nbsp;&nbsp;Popular Tags</h4>

  <div class="col-md-12 top-tags">
      <% Tag.top_tags.shuffle.each do |tag| %>
        <%= link_to tag.name, tag_path(tag),
        class: (Tag.size?(tag)) %>
      <% end %>
  </div>

  <br>

</div>

app/views/goals/new.html.erb
<h1>New Goal</h1>

<%= render 'form' %>

<%= link_to 'Back', goals_path %>

app/views/goals/show.html.erb
<!-- Jumbotron -->
<div class="jumbotron">
</div>

<div class="container">

  <div class="col-lg-12 goal-page">

  <!-- Create New Entry for Goal -->
  <% unless current_user != @user || @goal.completed? %>
    <p class="new-entry"><%= link_to "New Entry", new_goal_entry_path(@goal), class: 'btn btn-primary' %></p>
  <% end %>

  <!-- Edit & Destroy links -->
  <%= render 'control' %>

  <div class="user-info text-center">
  <% if @goal.private? %><p><small><em>private</em></small></p><% end %>

  <!-- User Avatar -->
  <p><%= image_tag @user.gravatar_url, class: 'avatar goal-avatar' %></p>

  <!-- Username & Goal -->
  <p class="user-goal">
    <strong><%= link_to @user.username.titleize, @user %><%= " wants to #{@goal.description}" %></strong>
  </p>

    <!-- Mark Goal as completed links. -->
    <%= render 'completed' %>

    <!-- Follow/Unfollow Buttons -->
    <p>
      <% if user_signed_in? && current_user != @user %>
        <% if current_user.following?(@user) %>
          <%= render partial: 'friendships/unfollow' %>
        <% else %>
          <%= render partial: 'friendships/follow' %>
        <% end %>
      <% end %>
    </p>

  </div>

  <h4 class="entries-title"><span class='glyphicon glyphicon-pencil'></span>&nbsp;&nbsp;Entries</h4>

  <!-- Show entries for goal -->
  <%= render 'entries' %>

  <p class="social">
    <%= social_share_button_tag("Carpe Diem: #{@goal.description}", url: @goal) %>
  </p>

  <h4 class="goal-tags-title"><span class='glyphicon glyphicon-tags'></span>&nbsp;&nbsp;Tags</h4>

  <div class="col-md-12 goal-tags">
     <% @goal.tags.each do |tag| %>
      <strong><%= link_to tag.name, tag_path(tag), class: 'tag' %></strong>
     <% end %>
  </div>

  </div>
</div>